apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: railsgoat
  name: rails-ingress
spec:
  rules:
  - host: railsgoat-rsp.com
    http:
      paths:
      - path: /
        backend:
          serviceName: rails
          servicePort: 3000