apiVersion: v1
kind: Service
metadata:
  namespace: railsgoat
  name: rails
spec:
  selector:
    app: rails
  type: NodePort
  ports:
  - port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: railsgoat
  name: rails
spec:
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
      - name: rails
        image: hnts/railsgoat:latest
        imagePullPolicy: Never
        command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
        envFrom:
        - configMapRef:
            name: rails-config
        ports:
        - containerPort: 3000