name: Brakeman

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - name: Install gems
        run: |
          gem install brakeman
      - name: brakeman report
        run: |
          cd railsgoat
          brakeman || exit 0